### ISSUE TITLE
[BUG] if memory block is set to RW, default value will be cleared by reset

### ISSUE THREAD

**Issue by shazz** [docmarionum1/py65emu#5]
Hi,

When I define a memory block with the flag ReadOnly to False, as soon as the CPU is started, mmu.reset() is called so that the default value set in the block is then deleted. Maybe would be better to clear at reset then rewrite the block default bytes?

**Comment by docmarionum1** [comment]
Hi @shazz . Can you give an example of the behavior you'd expect?

`mmu.reset()` by design is supposed to _zero_ all bytes in writable (`readonly=False`) blocks.

**Comment by shazz** [comment]
Let me explain how I use your really useful library (I love the simple interface)
In fact, `py65emu` is used as a plugin to a kind of 6502 cross-assembler, it allows me to unit test my code without testing on a complete C64 emulator. 

I simply:
- generate the bytecode of some parts of my code (a routine, a loop,...)
- pass it to py65emu as `BytesIO` object
- define the `mmu` (low_ram, my bytecode, hi_ram)
- define the `cpu` and set the start address to the bytecode start address
- call step on the `cpu` until it reaches the bytecode end address or a `brk` (else `py65emu` is going wild)
- use some `assert` statements between the `mmu` content (`mmu.read()`) and the expected result to check if my assembly code is correct

So it means that the bytecode I define in the `mmu` is read/write, not read-only (my code updates memory portions, even sometimes itself).

And as your code at init resets all R/W `mmu` sections, my bytecode got deleted before being executed.
That's why I patched this part of your code to avoid it.

Does it make sense? Not sure I'm really clear... tell me :)

**Comment by docmarionum1** [comment]
Ah, I see now. You're right, I'm calling reset in the `__init__` of the CPU.

I don't think that's necessary to do, so I've pushed a [commit ](https://github.com/docmarionum1/py65emu/commit/b611215c2034f099844c237589658d4a39563b08) removing it.

Let me know if this solves your issue.
