### ISSUE TITLE
array.array.fromstring() has been removed from Pythoin 3.9

### ISSUE THREAD

**Issue by kidmirage** [docmarionum1/py65emu#8]
So the code in mmu.py:

       elif value is not None:
            a = array.array('B')
            a.fromstring(value.read())
            for i in range(len(a)):
                newBlock['memory'][i+valueOffset] = a[i]

no longer works. I replaced mine with:

      elif value is not None:
            data = value.read().split()
            for i in range(len(data)):
                newBlock['memory'][i+valueOffset] = int(data[i], 16)

**Comment by chrissawer** [comment]
I opened a PR to fix this. Unfortunately your suggestion didn't work for me, I made a simpler change to use array.frombytes although this will only work on python3.

https://github.com/docmarionum1/py65emu/pull/9

**Comment by docmarionum1** [comment]
Thank you @kidmirage for raising the issue and @chrissawer for fixing!
